<?php

require_once('Menu.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-08 at 17:47:42.
 */
class MenuTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Menu
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Menu('inc/inventario.menu');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Menu::insertaMenu
     * @todo   Implement testInsertaMenu().
     */
    public function testInsertaMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>